AWSTemplateFormatVersion: '2010-09-09'
Description: 'Twilio Patient Appointment Management Bucket'


Parameters:


  ParameterApplicationName:
    Type: String

  ParameterCustomerCode:
    Type: String

  ParameterS3Bucket:
    Type: String


Outputs:

  PatientAppointmentManagementBucketName:
    Value: !Ref ResourceS3Bucket


Resources:


  ResourceS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref ParameterS3Bucket
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: 'DeleteQueryResultsAfter1Day'
            Prefix: 'query-results/'
            Status: Enabled
            ExpirationInDays: 1

  ResourceS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ParameterS3Bucket
      PolicyDocument:
        Statement:
          - Sid: 'DenyUnencryptedPut'
            Effect: Deny
            Action:
              - s3:PutObject
            Principal: '*'
            Resource:
              - !Sub 'arn:aws:s3:::${ParameterS3Bucket}/*'
            Condition:
              'Null':
                s3:x-amz-server-side-encryption: true
          - Sid: 'ForceSecureTransport'
            Effect: Deny
            Action:
              - s3:*
            Principal: '*'
            Resource:
              - !Sub 'arn:aws:s3:::${ParameterS3Bucket}'
              - !Sub 'arn:aws:s3:::${ParameterS3Bucket}/*'
            Condition:
              Bool:
                aws:SecureTransport: false

  PolicyForDeployer:
    Type: AWS::IAM::ManagedPolicy
    DeletionPolicy: Delete
    Properties:
      ManagedPolicyName: !Sub 'twilio-${ParameterApplicationName}-policy-s3-${ParameterCustomerCode}'
      Users:
        - !ImportValue 'PatientAppointmentManagementDeployerUser'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'S3ObjectPermissions'
            Effect: Allow
            Action:
              - s3:DeleteObject
              - s3:GetObject
              - s3:PutObject
            Resource:
              - !Sub 'arn:aws:s3:::${ParameterS3Bucket}/*'
          - Sid: 'S3BucketPermissions'
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Sub 'arn:aws:s3:::${ParameterS3Bucket}'
